- name: set required variables
  become_user: "{{ main_user }}"
  set_fact:
    vim_dir: "{{ ansible_env.HOME }}/.vim"
    vimrc: "{{ ansible_env.HOME }}/.vimrc"

- name: install required packages
  become: true
  ansible.builtin.package:
    name:
      - vim
      - fonts-powerline
      - fzf
    state: present

- name: ensure .vim/{autoload,bundle} directory exists
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
  loop:
    - "{{ vim_dir }}"
    - "{{ vim_dir }}/autoload"
    - "{{ vim_dir }}/bundle"

- name: check if autoload/pathogen.vim file exists
  stat:
    path: "{{ vim_dir }}/autoload/pathogen.vim"
  register: pathogen_vim

- name: ensure Pathogen is in place
  when: not pathogen_vim.stat.exists
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ vim_dir }}/autoload/pathogen.vim"

- name: deploy plugins
  become: true
  git:
    dest: "{{ vim_dir }}/bundle/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
    recursive: no
  loop:
    - name: vim-airline
      url: https://github.com/vim-airline/vim-airline
    - name: nerdtree
      url: https://github.com/preservim/nerdtree
    - name: fzf-vim
      url: https://github.com/junegunn/fzf.vim
    - name: vim-gitgutter
      url: https://github.com/airblade/vim-gitgutter
    - name: vim-fugitive
      url: https://github.com/tpope/vim-fugitive
    - name: vim-floaterm
      url: https://github.com/voldikss/vim-floaterm
