- name: install required system packages
  become: true
  ansible.builtin.package:
    name:
      - ca-certificates
    state: present
    update_cache: true

- name: check if docker.asc file exists
  stat:
    path: "/etc/apt/keyrings/docker.asc"
  register: docker_asc

- name: create directory and add Docker gpg apt key
  when: not docker_asc.stat.exists
  block:
    - name: ensure /etc/apt/keyrings/ directory exists with correct permissions
      become: true
      file:
        dest: "/etc/apt/keyrings/"
        state: directory
        mode: 0755

    - name: Add Docker GPG apt Key
      become: true
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: 0644

- name: check if docker repo file exists
  stat:
    path: "/etc/apt/sources.list.d/docker.list"
  register: docker_list

- name: create directory and add Docker gpg apt key
  when: not docker_list.stat.exists
  block:
    - name: add Docker repository to APT sources
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
        state: present
        filename: "docker"

    - name: update apt and install Docker packages
      become: true
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

- name: add user to the Docker group
  become: true
  user:
    name: "{{ main_user }}"
    groups: docker
    append: yes
